"""
Structured presentation builder for MIRA responses.

This layer keeps the KPI calculations in the existing dashboard services, but
reshapes them into a management-friendly response model that the frontend can
render as a dashboard summary instead of a plain text block.
"""

from __future__ import annotations

from datetime import datetime

from ..core import context as ctx

_RESPONSE_TYPE_ALIASES = {
    "monthly_summary": "monthly_summary",
    "monthly summary": "monthly_summary",
    "downtime_summary": "downtime_summary",
    "downtime summary": "downtime_summary",
    "pm_schedule_summary": "pm_schedule_summary",
    "pm schedule summary": "pm_schedule_summary",
    "spare_parts_summary": "spare_parts_summary",
    "spare parts summary": "spare_parts_summary",
    "work_order_summary": "work_order_summary",
    "work order summary": "work_order_summary",
}

_INTENT_DEFAULT_TYPES = {
    "monthly_summary": "monthly_summary",
    "mttr": "downtime_summary",
    "mtbf": "downtime_summary",
    "open_work_orders": "work_order_summary",
    "preventive_corrective": "downtime_summary",
    "data_quality": "downtime_summary",
    "pm_schedule": "pm_schedule_summary",
    "stage_compare": "downtime_summary",
    "work_order_search": "work_order_summary",
    "report_draft": "monthly_summary",
}

_RESPONSE_LABELS = {
    "monthly_summary": "Monthly Summary",
    "downtime_summary": "Downtime Summary",
    "pm_schedule_summary": "PM Schedule Summary",
    "spare_parts_summary": "Spare Parts Summary",
    "work_order_summary": "Work Order Summary",
}

_RESPONSE_TITLES = {
    "monthly_summary": "Maintenance Performance Summary",
    "downtime_summary": "Downtime and Work Order Summary",
    "pm_schedule_summary": "PM Schedule Performance Summary",
    "spare_parts_summary": "Spare Parts Performance Summary",
    "work_order_summary": "Work Order Performance Summary",
}

_AI_PLACEHOLDER = (
    "Detailed explanation, work order description analysis, possible operation-related patterns, "
    "and maintenance risk insights will be generated by Ollama in the next phase."
)


def build_presentation(
    intent: str,
    data: dict,
    filters: dict | None,
    *,
    mode: str = "kpi_summary",
    provider_name: str = "mock",
    response_type: str | None = None,
    question: str | None = None,
) -> dict:
    """Return a structured UI model for the MIRA frontend."""
    normalized_filters = ctx.normalize_filters(filters)
    focus = _canonical_response_type(response_type, intent)
    if intent == "work_order_search" or mode == "limited_filtered_rows":
        return _build_work_order_search_presentation(data, normalized_filters, provider_name, question)
    if "work_orders" in data and "pm_schedule" in data:
        return _build_management_presentation(data, normalized_filters, provider_name, focus, question)
    if intent == "pm_schedule":
        return _build_pm_only_presentation(data, normalized_filters, provider_name, question)
    if intent in {"mttr", "mtbf", "open_work_orders", "preventive_corrective", "data_quality"}:
        return _build_downtime_only_presentation(intent, data, normalized_filters, provider_name, question)
    if intent == "stage_compare":
        return _build_stage_compare_presentation(data, normalized_filters, provider_name)
    return _build_generic_presentation(intent, data, normalized_filters, provider_name, question)


def _canonical_response_type(response_type: str | None, intent: str) -> str:
    text = str(response_type or "").strip().lower()
    if text:
        return _RESPONSE_TYPE_ALIASES.get(text, _INTENT_DEFAULT_TYPES.get(intent, "monthly_summary"))
    return _INTENT_DEFAULT_TYPES.get(intent, "monthly_summary")


def _stage_label(stage: str | None) -> str:
    return {"all": "All Stages", "stage1": "Stage 1", "stage2": "Stage 2"}.get(stage, stage or "All Stages")


def _response_title(focus: str) -> str:
    return _RESPONSE_TITLES.get(focus, "Maintenance Performance Summary")


def _response_label(focus: str) -> str:
    return _RESPONSE_LABELS.get(focus, "Summary")


def _scope_label(filters: dict) -> str:
    parts = [_stage_label(filters.get("stage"))]
    if filters.get("mainAssetGroup"):
        parts.append(str(filters["mainAssetGroup"]))
    if filters.get("subAssetGroup"):
        parts.append(str(filters["subAssetGroup"]))
    return " · ".join(parts)


def _metric(label: str, raw, *, display: str | None = None, tone: str = "neutral", note: str | None = None) -> dict:
    return {
        "label": label,
        "raw": raw,
        "value": display if display is not None else _display_value(raw),
        "tone": tone,
        "note": note,
    }


def _kpi_card(label: str, raw, helper: str, status: str = "neutral", *, display: str | None = None) -> dict:
    return {
        "label": label,
        "raw": raw,
        "value": display if display is not None else _display_value(raw),
        "display": display if display is not None else _display_value(raw),
        "helper": helper,
        "note": helper,
        "status": status,
        "tone": status,
    }


def _display_value(value) -> str:
    if value is None:
        return "Not available"
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if isinstance(value, int):
        return f"{value:,}"
    if isinstance(value, float):
        if abs(value - round(value)) < 1e-9:
            return f"{int(round(value)):,}"
        return f"{value:,.2f}"
    text = str(value).strip()
    return text or "Not available"


def _hours(value) -> str:
    return "Not available" if value is None else f"{float(value):,.2f} h"


def _percent(value) -> str:
    return "Not available" if value is None else f"{float(value):,.1f}%"


def _currency(value, code: str = "THB") -> str:
    return "Not available" if value is None else f"{code} {float(value):,.0f}"


def _ratio_display(left, right) -> str:
    return f"{_display_value(left)} / {_display_value(right)}"


def _severity_breakdown_display(items: list[dict] | None) -> str:
    rows = []
    for item in items or []:
        label = str(item.get("label") or "").strip()
        count = item.get("count") if "count" in item else item.get("work_order_count")
        if not label:
            continue
        rows.append(f"{label}: {_display_value(count)}")
    return ", ".join(rows[:4]) if rows else "No severity split recorded"


def _ratio_tone(value, *, good: float, watch: float) -> str:
    if value is None:
        return "neutral"
    if value >= good:
        return "good"
    if value >= watch:
        return "watch"
    return "critical"


def _reverse_ratio_tone(value, *, good: float, watch: float) -> str:
    if value is None:
        return "neutral"
    if value <= good:
        return "good"
    if value <= watch:
        return "watch"
    return "critical"


def _consumption_change_tone(value) -> str:
    if value is None:
        return "neutral"
    if value <= 0:
        return "good"
    if value <= 10:
        return "watch"
    return "critical"


def _source_note(mode: str) -> str:
    if mode == "limited_filtered_rows":
        return "Based on limited, filtered work-order rows and approved dashboard KPIs"
    return "Based on verified dashboard KPI summary"


def _provider_note(provider_name: str) -> str:
    return f"MIRA Draft ({provider_name})"


def _generated_timestamp() -> str:
    return datetime.now().astimezone().strftime("%d %b %Y, %I:%M %p")


def _status_badges(provider_name: str) -> list[dict]:
    return [
        {"label": "Read-only", "tone": "muted"},
        {"label": "Draft for review", "tone": "accent"},
        {"label": _provider_note(provider_name), "tone": "light"},
    ]


def _compose_response(
    *,
    focus: str,
    period: str,
    filters: dict,
    provider_name: str,
    source_note: str,
    kpi_cards: list[dict],
    sections: dict,
    priority_follow_up: list[str],
    view_data_used: dict,
    action_items: list[dict] | None = None,
    question: str | None = None,
    data_notes: list[str] | None = None,
) -> dict:
    data_notes = list(data_notes or [])
    response = {
        "response_type": _response_label(focus),
        "title": _response_title(focus),
        "period": period,
        "scope": _scope_label(filters),
        "source_note": source_note,
        "status_badges": _status_badges(provider_name),
        "question": question or "",
        "kpi_cards": kpi_cards,
        "action_items": action_items or [],
        "sections": sections,
        "priority_follow_up": priority_follow_up[:5],
        "ai_explanation_placeholder": _AI_PLACEHOLDER,
        "view_data_used": view_data_used,
        "data_notes": data_notes,
    }
    # Keep compatibility with earlier frontend/tests.
    response["downtime_summary"] = sections.get("downtime_work_order_summary")
    response["pm_schedule_summary"] = sections.get("pm_schedule_summary")
    response["spare_parts_summary"] = sections.get("spare_parts_summary")
    return response


def _build_management_presentation(data: dict, filters: dict, provider_name: str, focus: str, question: str | None) -> dict:
    period = data.get("window") or ctx.month_label(filters)
    downtime_section = _build_downtime_section(data, period)
    pm_section = _build_pm_section(data, period)
    spare_section = _build_spare_section(data, period)
    data_notes = _management_data_notes(data)

    sections = {
        "downtime_work_order_summary": downtime_section,
        "pm_schedule_summary": pm_section,
        "spare_parts_summary": spare_section,
    }

    return _compose_response(
        focus=focus,
        period=period,
        filters=filters,
        provider_name=provider_name,
        source_note=_source_note("kpi_summary"),
        kpi_cards=_build_management_kpi_cards(data),
        action_items=_build_action_items(data),
        sections=sections,
        priority_follow_up=_build_priority_follow_up(data),
        view_data_used=_management_view_data_used(data, filters, data_notes),
        question=question,
        data_notes=data_notes,
    )


def _build_downtime_section(data: dict, period: str) -> dict:
    """Overview-card version: 4 key metrics only (Open, Closed, Rate, Carry-over)."""
    work_orders = data.get("work_orders") or {}
    summary = data.get("downtime_summary") or {}
    open_count = work_orders.get("open")
    closed_count = work_orders.get("closed")
    closure_rate = work_orders.get("closure_rate_pct") or summary.get("closure_rate_pct")
    opening_backlog = summary.get("carry_over_open_mr", summary.get("opening_backlog_count"))
    missing_asset = summary.get("missing_asset_count") or 0
    general_area = summary.get("general_area_asset_count") or 0
    in_progress = summary.get("in_progress_count")
    new_count = summary.get("new_count")
    finished = summary.get("finished_count")
    confirm = summary.get("confirm_count")
    open_note = (
        f"In Progress {_display_value(in_progress)} + New {_display_value(new_count)}"
        if in_progress is not None else "Outstanding in selected period"
    )
    closed_note = (
        f"Finished {_display_value(finished)} + Confirm {_display_value(confirm)}"
        if finished is not None else "Raised in selected period and now closed / confirmed"
    )
    dq_parts = []
    if missing_asset:
        dq_parts.append(f"{_display_value(missing_asset)} MR missing asset IDs")
    if general_area:
        dq_parts.append(f"{_display_value(general_area)} general-area entries")
    attention_note = ("Data quality: " + ", ".join(dq_parts)) if dq_parts else None
    cr = closure_rate or 0
    backlog = opening_backlog or 0
    if cr >= 85 and backlog == 0:
        health_status = "Healthy"
    elif cr >= 70:
        health_status = "Watch"
    else:
        health_status = "Attention"
    return {
        "title": "Downtime / Work Order Summary",
        "subtitle": "MR activity and closure status for selected period.",
        "health_status": health_status,
        "attention_note": attention_note,
        "metrics": [
            _metric("Open / In Progress", open_count,
                    tone=_reverse_ratio_tone(open_count, good=0, watch=10), note=open_note),
            _metric("Closed / Confirmed", closed_count, tone="good", note=closed_note),
            _metric("Closure Rate", closure_rate, display=_percent(closure_rate),
                    tone=_ratio_tone(closure_rate, good=85, watch=70),
                    note=f"{_display_value(work_orders.get('total'))} MR raised in {period}"),
            _metric("Carry-over Open MR", opening_backlog,
                    tone=_reverse_ratio_tone(opening_backlog, good=0, watch=25),
                    note=f"Raised before {period} and still open"),
        ],
        "summary": (
            f"{_display_value(work_orders.get('total'))} MR raised in {period}. "
            f"{_display_value(closed_count)} closed / confirmed, {_display_value(open_count)} open or in progress "
            f"(closure rate {_percent(closure_rate)}). "
            f"Carry-over open MR: {_display_value(opening_backlog)}."
        ),
        "footnote": (
            "Detailed asset, severity, WO-created %, and functional-location breakdowns "
            "are available on the Downtime and Machine Explorer pages."
        ),
    }


def _build_pm_section(data: dict, period: str) -> dict:
    pm = data.get("pm_schedule") or {}
    compliance = pm.get("compliance_pct")
    completed = pm.get("completed") or 0
    scheduled = pm.get("total_scheduled") or 0
    overdue = pm.get("overdue") or 0
    zero_completion = completed == 0 and scheduled > 0
    completion_tone = "watch" if zero_completion else ("good" if completed > 0 else "neutral")
    completion_note = (
        "Shows 0 — verify completion records before assuming non-compliance"
        if zero_completion else "Manual Done only"
    )
    if compliance is not None and compliance >= 90 and overdue == 0:
        health_status = "Healthy"
    elif compliance is not None and compliance >= 75:
        health_status = "Watch"
    else:
        health_status = "Attention"
    return {
        "title": "PM Schedule Summary",
        "health_status": health_status,
        "completion_warning": (
            "PM completion shows 0. This may indicate missing manual completion records, "
            "not confirmed non-compliance. Verify with the PM team before action."
            if zero_completion else None
        ),
        "attention_note": (
            "PM completion shows 0 — may indicate missing records, not confirmed non-compliance."
            if zero_completion else None
        ),
        "metrics": [
            _metric("PM Due This Month", pm.get("due_this_month")),
            _metric("PM Completed", pm.get("completed"),
                    tone=completion_tone, note=completion_note),
            _metric("PM Overdue", pm.get("overdue"),
                    tone=_reverse_ratio_tone(pm.get("overdue"), good=0, watch=20)),
            _metric("PM Compliance", compliance, display=_percent(compliance),
                    tone=_ratio_tone(compliance, good=90, watch=75)),
        ],
        "summary": (
            f"{_display_value(scheduled)} PM tasks scheduled. "
            f"{_display_value(pm.get('due_this_month'))} due this month, "
            f"{_display_value(pm.get('completed'))} completed, "
            f"{_display_value(pm.get('overdue'))} overdue. "
            f"Compliance is {_percent(compliance)}."
            + (" PM completion shows 0 — verify records." if zero_completion else "")
        ),
        "footnote": "PM is counted as completed only when manually marked Done in the PM schedule.",
    }


def _build_spare_section(data: dict, period: str) -> dict:
    spare = data.get("spare_parts") or {}
    yoy = spare.get("yoy_consumption_pct")
    top_part = spare.get("top_consumed_part")

    # In-stock value: show "Missing cost data" when items exist but value is 0.
    # On-hand quantities may exist without unit costs in the inventory table.
    in_stock_items = spare.get("current_in_stock_items") or 0
    raw_value = spare.get("current_in_stock_value")
    value_is_zero_with_stock = (raw_value is not None and raw_value == 0 and in_stock_items > 0)
    if value_is_zero_with_stock:
        in_stock_value_display = "Missing cost data"
        in_stock_value_note = (
            "On-hand items recorded but unit costs unavailable in inventory table. "
            "Estimated value from PO price history not yet implemented."
        )
        in_stock_value_tone = "watch"
    else:
        in_stock_value_display = _currency(raw_value)
        in_stock_value_note = None
        in_stock_value_tone = "neutral"

    attention_note = (
        "Inventory value unavailable — items on hand but unit costs not recorded."
        if value_is_zero_with_stock else None
    )
    health_status = "Watch" if value_is_zero_with_stock else "Healthy"
    return {
        "title": "Spare Parts Summary",
        "health_status": health_status,
        "attention_note": attention_note,
        "metrics": [
            _metric("In-Stock Spare Parts", spare.get("current_in_stock_items")),
            _metric("In-Stock Value", raw_value,
                    display=in_stock_value_display,
                    tone=in_stock_value_tone,
                    note=in_stock_value_note),
            _metric("Drawn from Store", spare.get("drawn_from_store_value"),
                    display=_currency(spare.get("drawn_from_store_value"))),
            _metric("Non-Stock Purchase", spare.get("non_stock_value"),
                    display=_currency(spare.get("non_stock_value"))),
        ],
        "summary": (
            f"{_display_value(in_stock_items)} in-stock items. "
            f"Drawn-from-store: {_currency(spare.get('drawn_from_store_value'))}. "
            f"Non-stock: {_currency(spare.get('non_stock_value'))}."
        ),
        "footnote": spare.get("services_note") or "Non-Stock = direct purchases not held in store.",
    }


def _build_management_kpi_cards(data: dict) -> list[dict]:
    """Four headline KPI cards shown at the top of the executive summary."""
    work_orders = data.get("work_orders") or {}
    downtime = data.get("downtime_summary") or {}
    opening_backlog = downtime.get("carry_over_open_mr", downtime.get("opening_backlog_count"))
    return [
        _kpi_card("MR Raised", work_orders.get("total"),
                  "Raised in the selected period", "neutral"),
        _kpi_card("Open / In Progress", work_orders.get("open"),
                  "Outstanding maintenance",
                  _reverse_ratio_tone(work_orders.get("open"), good=0, watch=10)),
        _kpi_card("Carry-over Open MR", opening_backlog,
                  "From before the period — still unresolved",
                  _reverse_ratio_tone(opening_backlog, good=0, watch=25)),
        _kpi_card("Closure Rate", downtime.get("closure_rate_pct"),
                  "Closed / Confirmed ÷ MR Raised",
                  _ratio_tone(downtime.get("closure_rate_pct"), good=85, watch=70),
                  display=_percent(downtime.get("closure_rate_pct"))),
    ]


def _build_action_items(data: dict) -> list[dict]:
    """Structured action items for the management overview action table."""
    work_orders = data.get("work_orders") or {}
    pm = data.get("pm_schedule") or {}
    downtime = data.get("downtime_summary") or {}
    items = []

    open_count = work_orders.get("open") or 0
    if open_count > 0:
        items.append({
            "priority": "High",
            "action": f"Review {_display_value(open_count)} open / in-progress MR",
            "reason": "Outstanding maintenance not yet closed",
        })

    overdue_pm = pm.get("overdue") or 0
    if overdue_pm > 0:
        items.append({
            "priority": "High",
            "action": f"Action {_display_value(overdue_pm)} overdue PM tasks",
            "reason": f"PM compliance at {_percent(pm.get('compliance_pct'))}",
        })

    missing_asset = downtime.get("missing_asset_count") or 0
    if missing_asset > 0:
        items.append({
            "priority": "Medium",
            "action": f"Correct {_display_value(missing_asset)} MR records missing Asset ID",
            "reason": "Required for reliable asset-level reporting",
        })

    completed = pm.get("completed") or 0
    scheduled = pm.get("total_scheduled") or 0
    if completed == 0 and scheduled > 0:
        items.append({
            "priority": "Medium",
            "action": "Validate PM completion records",
            "reason": "0 completed may indicate missing records, not confirmed non-compliance",
        })

    carry_over = downtime.get("carry_over_open_mr", downtime.get("opening_backlog_count")) or 0
    if carry_over > 0:
        items.append({
            "priority": "Medium",
            "action": f"Review {_display_value(carry_over)} carry-over open MR",
            "reason": "Raised before selected period and still unresolved",
        })

    general_area = downtime.get("general_area_asset_count") or 0
    if general_area > 0:
        items.append({
            "priority": "Low",
            "action": f"Update {_display_value(general_area)} MR with general-area asset tags",
            "reason": "General area entries reduce asset-level traceability",
        })

    return items[:6]


def _build_priority_follow_up(data: dict) -> list[str]:
    work_orders = data.get("work_orders") or {}
    pm = data.get("pm_schedule") or {}
    downtime = data.get("downtime_summary") or {}
    spare = data.get("spare_parts") or {}
    items = []
    if (work_orders.get("open") or 0) > 0:
        items.append(f"Review outstanding MR / open work orders; {_display_value(work_orders.get('open'))} remain open.")
    if (downtime.get("opening_backlog_count") or 0) > 0:
        items.append(f"Review {_display_value(downtime.get('opening_backlog_count'))} carry-over open MR from before the selected period.")
    if pm.get("compliance_pct") is not None and (pm.get("compliance_pct") < 90 or (pm.get("overdue") or 0) > 0):
        items.append(f"Follow up low PM compliance at {_percent(pm.get('compliance_pct'))} and {_display_value(pm.get('overdue'))} overdue PM tasks.")
    if downtime.get("top_asset_by_mr_count_name") or downtime.get("focus_asset_name"):
        items.append(
            f"Check top asset {downtime.get('top_asset_by_mr_count_name') or downtime.get('focus_asset_name') or 'available in dashboard'} "
            f"and functional location {downtime.get('top_functional_location_name') or downtime.get('top_work_order_machine_group') or 'available in dashboard'}."
        )
    if (data.get("data_reliability_issue_count") or 0) > 0:
        items.append(f"Validate {_display_value(data.get('data_reliability_issue_count'))} records flagged for data reliability.")
    if spare.get("top_consumed_part") or ((spare.get("yoy_consumption_pct") or 0) > 5):
        items.append("Review high-value spare-parts consumption, especially non-stock and service-related spend.")
    return items[:5]


def _management_data_notes(data: dict) -> list[str]:
    notes = []
    pm = data.get("pm_schedule") or {}
    downtime = data.get("downtime_summary") or {}
    spare = data.get("spare_parts") or {}
    if (downtime.get("missing_asset_count") or 0) > 0:
        notes.append(f"{_display_value(downtime.get('missing_asset_count'))} selected-period MR records are missing Asset ID.")
    if (downtime.get("general_area_asset_count") or 0) > 0:
        breakdown = downtime.get("general_area_asset_breakdown") or []
        detail = ", ".join(f"{b.get('name')} {b.get('count')}" for b in breakdown[:3])
        notes.append(
            f"{_display_value(downtime.get('general_area_asset_count'))} selected-period MR records use general area / placeholder "
            f"asset names rather than a true machine asset" + (f" ({detail})." if detail else ".")
        )
    if (downtime.get("missing_functional_location_count") or 0) > 0:
        notes.append(f"{_display_value(downtime.get('missing_functional_location_count'))} selected-period MR records could not be mapped to functional location.")
    if (downtime.get("unknown_status_count") or 0) > 0:
        notes.append(f"{_display_value(downtime.get('unknown_status_count'))} selected-period MR records have an unmapped status.")
    if (pm.get("missing_mapping") or 0) > 0:
        notes.append(f"{_display_value(pm.get('missing_mapping'))} PM records are still missing mapping.")
    if (pm.get("needs_review") or 0) > 0:
        notes.append(f"{_display_value(pm.get('needs_review'))} PM records still need review.")
    notes.extend(spare.get("data_notes") or [])
    return notes


def _management_view_data_used(data: dict, filters: dict, notes: list[str]) -> dict:
    spare = data.get("spare_parts") or {}
    work_orders = data.get("work_orders", {}) or {}
    downtime = data.get("downtime_summary", {}) or {}
    _w = ctx.resolved_window(filters)
    applied = [
        f"Period: {data.get('window') or ctx.month_label(filters)}",
        f"Period mode: {filters.get('period_mode')}",
        f"Date range: {_w['start_date'].isoformat()} to {_w['end_date'].isoformat()}",
        f"Scope: {_scope_label(filters)}",
    ]
    return {
        "period_mode": filters.get("period_mode"),
        "date_range": f"{_w['start_date'].isoformat()} to {_w['end_date'].isoformat()}",
        "source_tables": [
            "Downtime dashboard work-order rows",
            "PM schedule task payload",
            "Spare parts overview payload",
            "Project transactions history",
        ],
        "filters_applied": applied,
        "rows_loaded": [
            _metric("Selected-period MR loaded", work_orders.get("total")),
            _metric("Carry-over open MR", downtime.get("opening_backlog_count")),
            _metric("PM tasks loaded", data.get("pm_schedule", {}).get("total_scheduled")),
            _metric("Inventory rows loaded", spare.get("inventory_rows_loaded")),
            _metric("PO rows loaded", spare.get("po_rows_loaded")),
            _metric("Project transaction rows loaded", spare.get("project_transaction_rows_loaded")),
        ],
        "rows_after_filter": [
            _metric("Filtered PO rows", spare.get("po_rows_after_filter")),
            _metric("Filtered store-draw rows", spare.get("project_transaction_rows_after_filter")),
        ],
        "kpi_values_used": [
            _metric("MR Raised", work_orders.get("total")),
            _metric("Open / In Progress", work_orders.get("open")),
            _metric("Closed / Confirmed", work_orders.get("closed")),
            _metric("Closure Rate", downtime.get("closure_rate_pct"), display=_percent(downtime.get("closure_rate_pct"))),
            _metric("Preventive / Corrective", None, display=_ratio_display(downtime.get("preventive_count"), downtime.get("corrective_count"))),
            _metric("PM Compliance", data.get("pm_schedule", {}).get("compliance_pct"), display=_percent(data.get("pm_schedule", {}).get("compliance_pct"))),
        ],
        "last_refreshed": _generated_timestamp(),
        "data_warnings": notes,
    }


def _build_pm_only_presentation(data: dict, filters: dict, provider_name: str, question: str | None) -> dict:
    period = data.get("window") or ctx.month_label(filters)
    pm_data = {
        "window": period,
        "work_orders": {},
        "pm_schedule": {
            "total_scheduled": data.get("total_scheduled"),
            "completed": data.get("completed"),
            "due_this_month": data.get("due_this_month"),
            "overdue": data.get("overdue"),
            "backlog": data.get("backlog"),
            "compliance_pct": data.get("compliance_pct"),
            "missing_mapping": data.get("missing_mapping"),
            "needs_review": data.get("needs_review"),
        },
        "downtime_summary": {},
        "spare_parts": {},
    }
    notes = []
    if (data.get("missing_mapping") or 0) > 0:
        notes.append(f"{_display_value(data.get('missing_mapping'))} PM records are still missing mapping.")
    if (data.get("needs_review") or 0) > 0:
        notes.append(f"{_display_value(data.get('needs_review'))} PM records still need review.")
    sections = {
        "downtime_work_order_summary": None,
        "pm_schedule_summary": _build_pm_section(pm_data, period),
        "spare_parts_summary": None,
    }
    return _compose_response(
        focus="pm_schedule_summary",
        period=period,
        filters=filters,
        provider_name=provider_name,
        source_note=_source_note("kpi_summary"),
        kpi_cards=[
            _kpi_card("PM Scheduled", data.get("total_scheduled"), "Selected PM workload", "neutral"),
            _kpi_card("PM Completed", data.get("completed"), "Manual Done only", "good"),
            _kpi_card("PM Due This Month", data.get("due_this_month"), "Current month demand", "neutral"),
            _kpi_card("PM Overdue", data.get("overdue"), "Requires follow-up", _reverse_ratio_tone(data.get("overdue"), good=0, watch=20)),
            _kpi_card("PM Backlog", data.get("backlog"), "Pending backlog items", _reverse_ratio_tone(data.get("backlog"), good=0, watch=20)),
            _kpi_card("PM Compliance", data.get("compliance_pct"), "Manual completion rate", _ratio_tone(data.get("compliance_pct"), good=90, watch=75), display=_percent(data.get("compliance_pct"))),
        ],
        sections=sections,
        priority_follow_up=[
            f"Follow up low PM compliance at {_percent(data.get('compliance_pct'))}." if data.get("compliance_pct") is not None else "Review PM compliance.",
            f"Review {_display_value(data.get('overdue'))} overdue PM tasks." if (data.get("overdue") or 0) > 0 else "No overdue PM tasks are currently flagged.",
        ],
        view_data_used={
            "source_tables": ["PM schedule task payload"],
            "filters_applied": [f"Period: {period}", f"Scope: {_scope_label(filters)}"],
            "rows_loaded": [_metric("PM tasks loaded", data.get("total_scheduled"))],
            "rows_after_filter": [],
            "kpi_values_used": [
                _metric("PM Scheduled", data.get("total_scheduled")),
                _metric("PM Completed", data.get("completed")),
                _metric("PM Overdue", data.get("overdue")),
                _metric("PM Compliance", data.get("compliance_pct"), display=_percent(data.get("compliance_pct"))),
            ],
            "last_refreshed": _generated_timestamp(),
            "data_warnings": notes,
        },
        question=question,
        data_notes=notes,
    )


def _build_downtime_only_presentation(intent: str, data: dict, filters: dict, provider_name: str, question: str | None) -> dict:
    period = data.get("window") or ctx.month_label(filters)
    if intent == "open_work_orders":
        summary_data = {
            "window": period,
            "work_orders": {
                "total": data.get("total_work_orders"),
                "open": data.get("open_work_orders"),
                "closed": data.get("closed_work_orders"),
                "rejected": data.get("rejected_work_orders"),
                "closure_rate_pct": data.get("closure_rate_pct"),
                "open_rate_pct": data.get("open_rate_pct"),
            },
            "downtime_summary": {
                "carry_over_open_mr": data.get("carry_over_open_mr"),
                "opening_backlog_count": data.get("carry_over_open_mr"),
                "total_active_workload": data.get("total_active_workload"),
                "total_with_backlog_count": data.get("total_active_workload"),
                "preventive_count": data.get("preventive_count"),
                "corrective_count": data.get("corrective_count"),
                "wo_created_pct": data.get("wo_created_pct"),
                "top_asset_by_mr_count_name": data.get("top_asset_by_mr_count_name"),
                "top_asset_reason": data.get("top_asset_reason"),
                "top_functional_location_name": data.get("top_functional_location_name"),
                "top_functional_location_reason": data.get("top_functional_location_reason"),
                "severity_mix": data.get("severity_mix"),
                "data_quality_issue_count": data.get("requires_attention_count"),
            },
            "pm_schedule": {},
            "spare_parts": {},
        }
        notes = []
        if (data.get("requires_attention_count") or 0) > 0:
            notes.append(f"{_display_value(data.get('requires_attention_count'))} selected-period MR records have key data issues.")
        return _compose_response(
            focus="work_order_summary",
            period=period,
            filters=filters,
            provider_name=provider_name,
            source_note=_source_note("kpi_summary"),
            kpi_cards=_build_management_kpi_cards(summary_data),
            sections={
                "downtime_work_order_summary": _build_downtime_section(summary_data, period),
                "pm_schedule_summary": None,
                "spare_parts_summary": None,
            },
            priority_follow_up=[
                f"Review outstanding MR / open work orders; {_display_value(data.get('open_work_orders'))} remain open." if (data.get("open_work_orders") or 0) > 0 else "No open work orders are currently flagged.",
                f"Review carry-over open MR; {_display_value(data.get('carry_over_open_mr'))} remain from before the selected period." if (data.get("carry_over_open_mr") or 0) > 0 else "No carry-over open MR are currently flagged.",
            ],
            view_data_used={
                "source_tables": [str(data.get("source") or "Downtime dashboard work-order rows")],
                "filters_applied": [f"Period: {period}", f"Scope: {_scope_label(filters)}"],
                "rows_loaded": [
                    _metric("Selected-period MR loaded", data.get("total_work_orders")),
                    _metric("Carry-over open MR", data.get("carry_over_open_mr")),
                ],
                "rows_after_filter": [],
                "kpi_values_used": [
                    _metric("MR Raised", data.get("total_work_orders")),
                    _metric("Open / In Progress", data.get("open_work_orders")),
                    _metric("Closed / Confirmed", data.get("closed_work_orders")),
                    _metric("Closure Rate", data.get("closure_rate_pct"), display=_percent(data.get("closure_rate_pct"))),
                ],
                "last_refreshed": _generated_timestamp(),
                "data_warnings": notes,
            },
            question=question,
            data_notes=notes,
        )

    open_count = data.get("open_work_orders")
    total = data.get("total_work_orders")
    closed = data.get("closed_work_orders")
    mttr = data.get("overall_mttr_hours")
    mtbf = data.get("overall_average_mtbf_hours")
    notes = []
    if (data.get("requires_attention_count") or 0) > 0:
        notes.append(f"{_display_value(data.get('requires_attention_count'))} work orders were flagged for data reliability attention.")
    sections = {
        "downtime_work_order_summary": {
            "title": "Downtime / Work Order Summary",
            "metrics": [
                _metric("Total Work Orders", total),
                _metric("Open / Outstanding", open_count, tone=_reverse_ratio_tone(open_count, good=0, watch=10)),
                _metric("Closed Work Orders", closed, tone="good"),
                _metric("MTTR", mttr, display=_hours(mttr)),
                _metric("MTBF", mtbf, display=_hours(mtbf)),
            ],
            "summary": (
                f"{_display_value(total)} work orders were included in {period}, with {_display_value(open_count)} outstanding and "
                f"{_display_value(closed)} closed. MTTR was {_hours(mttr)} and MTBF was {_hours(mtbf)}."
            ),
            "visuals": [
                {
                    "type": "split_bar",
                    "label": "Open vs Closed Work Orders",
                    "items": [
                        {"label": "Closed", "value": closed or 0, "tone": "good"},
                        {"label": "Open", "value": open_count or 0, "tone": "critical"},
                    ],
                }
            ],
        },
        "pm_schedule_summary": None,
        "spare_parts_summary": None,
    }
    return _compose_response(
        focus="work_order_summary" if intent == "open_work_orders" else "downtime_summary",
        period=period,
        filters=filters,
        provider_name=provider_name,
        source_note=_source_note("kpi_summary"),
        kpi_cards=[
            _kpi_card("Work Orders", total, f"{_display_value(closed)} closed, {_display_value(open_count)} open", "neutral"),
            _kpi_card("Open WO / Outstanding MR", open_count, "Outstanding follow-up items", _reverse_ratio_tone(open_count, good=0, watch=10)),
            _kpi_card("MTTR", mttr, "Average repair duration", "neutral", display=_hours(mttr)),
            _kpi_card("MTBF", mtbf, "Average time between failures", "neutral", display=_hours(mtbf)),
        ],
        sections=sections,
        priority_follow_up=[
            f"Review outstanding MR / open work orders; {_display_value(open_count)} remain open." if (open_count or 0) > 0 else "No open work orders are currently flagged.",
            "Validate data reliability issues before reporting externally." if notes else "No major data reliability concerns were surfaced in this view.",
        ],
        view_data_used={
            "source_tables": [str(data.get("source") or "Downtime dashboard summary")],
            "filters_applied": [f"Period: {period}", f"Scope: {_scope_label(filters)}"],
            "rows_loaded": [_metric("Work orders loaded", total)],
            "rows_after_filter": [],
            "kpi_values_used": [
                _metric("WO", total),
                _metric("Open WO", open_count),
                _metric("MTTR", mttr, display=_hours(mttr)),
                _metric("MTBF", mtbf, display=_hours(mtbf)),
            ],
            "last_refreshed": _generated_timestamp(),
            "data_warnings": notes,
        },
        question=question,
        data_notes=notes,
    )


def _build_stage_compare_presentation(data: dict, filters: dict, provider_name: str) -> dict:
    period = data.get("window") or ctx.month_label(filters)
    stage1 = data.get("stage1") or {}
    stage2 = data.get("stage2") or {}
    s1_wo = ((stage1.get("open_work_orders") or {}).get("total_work_orders"))
    s2_wo = ((stage2.get("open_work_orders") or {}).get("total_work_orders"))
    sections = {
        "downtime_work_order_summary": {
            "title": "Downtime / Work Order Summary",
            "metrics": [
                _metric("Stage 1 Work Orders", s1_wo),
                _metric("Stage 2 Work Orders", s2_wo),
                _metric("Stage 1 MTTR", (stage1.get("mttr") or {}).get("overall_mttr_hours"), display=_hours((stage1.get("mttr") or {}).get("overall_mttr_hours"))),
                _metric("Stage 2 MTTR", (stage2.get("mttr") or {}).get("overall_mttr_hours"), display=_hours((stage2.get("mttr") or {}).get("overall_mttr_hours"))),
            ],
            "summary": (
                f"{period} comparison shows Stage 1 at {_display_value(s1_wo)} work orders and Stage 2 at "
                f"{_display_value(s2_wo)} work orders."
            ),
        },
        "pm_schedule_summary": None,
        "spare_parts_summary": None,
    }
    return _compose_response(
        focus="downtime_summary",
        period=period,
        filters={"stage": "all", "mainAssetGroup": filters.get("mainAssetGroup"), "subAssetGroup": filters.get("subAssetGroup")},
        provider_name=provider_name,
        source_note=_source_note("kpi_summary"),
        kpi_cards=[
            _kpi_card("Stage 1 Work Orders", s1_wo, "Selected period total", "neutral"),
            _kpi_card("Stage 2 Work Orders", s2_wo, "Selected period total", "neutral"),
            _kpi_card("Stage 1 MTTR", (stage1.get("mttr") or {}).get("overall_mttr_hours"), "Average repair duration", "neutral", display=_hours((stage1.get("mttr") or {}).get("overall_mttr_hours"))),
            _kpi_card("Stage 2 MTTR", (stage2.get("mttr") or {}).get("overall_mttr_hours"), "Average repair duration", "neutral", display=_hours((stage2.get("mttr") or {}).get("overall_mttr_hours"))),
        ],
        sections=sections,
        priority_follow_up=["Compare Stage 1 and Stage 2 workloads together with PM schedule and asset-level downtime for management action."],
        view_data_used={
            "source_tables": ["Downtime dashboard summary", "PM schedule task payload"],
            "filters_applied": [f"Period: {period}", "Scope: Stage 1 and Stage 2"],
            "rows_loaded": [],
            "rows_after_filter": [],
            "kpi_values_used": [
                _metric("Stage 1 WO", s1_wo),
                _metric("Stage 2 WO", s2_wo),
            ],
            "last_refreshed": _generated_timestamp(),
            "data_warnings": [],
        },
        data_notes=[],
    )


def _build_work_order_search_presentation(data: dict, filters: dict, provider_name: str, question: str | None) -> dict:
    period = data.get("window") or ctx.month_label(filters)
    total = data.get("total_matched")
    shown = data.get("returned_rows")
    truncated = bool(data.get("truncated"))
    notes = []
    if truncated:
        notes.append("The work-order list was capped for privacy and readability.")
    if total == 0:
        notes.append("No matching work orders were found for the selected filters.")
    sections = {
        "downtime_work_order_summary": {
            "title": "Downtime / Work Order Summary",
            "metrics": [
                _metric("Matched Rows", total),
                _metric("Rows Shown", shown),
                _metric("Row Cap", data.get("row_cap")),
            ],
            "summary": (
                f"Work-order search returned {_display_value(total)} matched rows for {period}, with {_display_value(shown)} shown in the response."
            ),
        },
        "pm_schedule_summary": None,
        "spare_parts_summary": None,
    }
    return _compose_response(
        focus="work_order_summary",
        period=period,
        filters=filters,
        provider_name=provider_name,
        source_note=_source_note("limited_filtered_rows"),
        kpi_cards=[
            _kpi_card("Matched Rows", total, "Rows matching current filters", "neutral"),
            _kpi_card("Rows Shown", shown, "Privacy-capped response rows", "neutral"),
            _kpi_card("Row Cap", data.get("row_cap"), "Maximum rows returned", "neutral"),
        ],
        sections=sections,
        priority_follow_up=["Narrow the filter if you want a shorter work-order list for management review."] if truncated else [],
        view_data_used={
            "source_tables": [str(data.get("source") or "Downtime work-order rows")],
            "filters_applied": [f"Period: {period}", f"Scope: {_scope_label(filters)}"],
            "rows_loaded": [_metric("Matched rows", total)],
            "rows_after_filter": [_metric("Rows shown", shown)],
            "kpi_values_used": [
                _metric("Matched Rows", total),
                _metric("Rows Shown", shown),
                _metric("Row Cap", data.get("row_cap")),
            ],
            "last_refreshed": _generated_timestamp(),
            "data_warnings": notes,
        },
        question=question,
        data_notes=notes,
    )


def _build_generic_presentation(intent: str, data: dict, filters: dict, provider_name: str, question: str | None) -> dict:
    period = data.get("window") or ctx.month_label(filters)
    sections = {
        "downtime_work_order_summary": None,
        "pm_schedule_summary": None,
        "spare_parts_summary": None,
    }
    return _compose_response(
        focus=_canonical_response_type(None, intent),
        period=period,
        filters=filters,
        provider_name=provider_name,
        source_note=_source_note("kpi_summary"),
        kpi_cards=[],
        sections=sections,
        priority_follow_up=[],
        view_data_used={
            "source_tables": [str(data.get("source") or "Dashboard KPI summary")],
            "filters_applied": [f"Period: {period}", f"Scope: {_scope_label(filters)}"],
            "rows_loaded": [],
            "rows_after_filter": [],
            "kpi_values_used": [],
            "last_refreshed": _generated_timestamp(),
            "data_warnings": [],
        },
        question=question,
        data_notes=[],
    )
