"""
MIRA configuration — safe local defaults.

All settings can be overridden via environment variables, but this prototype does
NOT require (and does not edit) any .env file. The defaults are deliberately the
safest possible: mock provider only, local LLM disabled, conservative row caps.
"""

from __future__ import annotations

import os


def _env_flag(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return str(raw).strip().lower() in {"1", "true", "yes", "on"}


# ── Provider selection ──────────────────────────────────────────────────────────
# "auto"       -> use local Ollama if it is running, else rule-based (default)
# "ollama"     -> force the local Ollama provider (still falls back per-call on error)
# "rule_based" -> rule-based mock (no LLM at all)
# "local"      -> localLlmProviderStub (disabled stub; requires explicit IT approval)
# Honour the spec's LLM_PROVIDER name as well as MIRA_PROVIDER.
_PROVIDER_RAW = (os.environ.get("LLM_PROVIDER") or os.environ.get("MIRA_PROVIDER") or "auto").strip().lower()
# "rule_based" / "rule-based" / "mock" all mean the deterministic rule-based provider.
PROVIDER_MODE = "mock" if _PROVIDER_RAW in ("rule_based", "rule-based", "mock") else _PROVIDER_RAW

# Hard gate for the local-LLM stub. Even if PROVIDER_MODE=="local", the stub stays
# inert unless this is explicitly enabled by an approver.
LOCAL_LLM_ENABLED = _env_flag("MIRA_LOCAL_LLM_ENABLED", False)

# ── Local Ollama (LLM wording only — never produces numbers) ─────────────────────
# Loopback host only; MIRA never sends data to an external service. Ollama receives
# the already-verified KPI JSON and only writes the human-readable wording around it.
# Honour both the spec's OLLAMA_BASE_URL and the MIRA_OLLAMA_HOST names.
OLLAMA_HOST = (
    os.environ.get("OLLAMA_BASE_URL")
    or os.environ.get("MIRA_OLLAMA_HOST")
    or "http://127.0.0.1:11434"
).strip().rstrip("/")
OLLAMA_BASE_URL = OLLAMA_HOST  # alias matching the spec
OLLAMA_MODEL = (os.environ.get("OLLAMA_MODEL") or os.environ.get("MIRA_OLLAMA_MODEL") or "qwen2.5:7b").strip()
OLLAMA_TIMEOUT_SECONDS = int(os.environ.get("MIRA_OLLAMA_TIMEOUT", "120"))

# MIRA system prompt — grounding rules for the LLM wording layer.
MIRA_SYSTEM_PROMPT = (
    "You are MIRA, a read-only Maintenance Intelligence and Reporting Assistant. "
    "You summarise verified maintenance dashboard metrics for engineering management. "
    "You must only use the metrics and issue classifications provided in the JSON. "
    "Do not invent numbers. Do not estimate missing values. Do not claim a root cause "
    "unless the data supports it. If data is missing or unclear, state that it is "
    "unavailable. Keep the wording concise, professional, and suitable for daily "
    "maintenance review."
)

# ── Privacy guard limits ────────────────────────────────────────────────────────
# Limited Filtered Rows Mode only — never the full dataset.
ROW_CAP_DEFAULT = int(os.environ.get("MIRA_ROW_CAP_DEFAULT", "15"))
ROW_CAP_MAX = int(os.environ.get("MIRA_ROW_CAP_MAX", "25"))

# Label stamped on every MIRA output.
DRAFT_LABEL = "Draft generated by MIRA for review"

# Disclaimer surfaced in responses / reports / docs.
MODEL_DISCLAIMER = (
    "Training a full Transformer model from scratch is not included in this "
    "prototype. MIRA is a controlled local assistant layer using dashboard KPI "
    "tools. A local LLM or approved AI service can be connected later if approved "
    "by IT."
)

# Default forward-looking window already used by the dashboard PM logic.
DEFAULT_STAGE = "all"
