"""
privacyGuardService — the gate every MIRA output passes through.

Responsibilities (per the MIRA spec):
  * Block full raw dataset transfer.
  * Limit returned rows for chatbot answers (10..ROW_CAP_MAX).
  * Remove unnecessary staff names, supplier names, sensitive remarks from rows.
  * Allow KPI summaries; allow limited filtered WO rows only when needed.
  * Mark all outputs as "Draft generated by MIRA for review".
  * Prevent API keys / secrets from being exposed.
  * Prevent full work-order records from being logged in the frontend console
    (the guard returns a `console_safe` flag + scrubbed payload the route uses).

Default-deny: work-order rows are projected onto a fixed allowlist of safe,
structured fields. Anything not on the list (free-text descriptions, staff /
vendor names, remarks, costs) is dropped.
"""

from __future__ import annotations

import re

from .. import config

# Structured, non-sensitive fields kept for Limited Filtered Rows Mode.
WORK_ORDER_ALLOWLIST = (
    "work_order_id",
    "asset_id",
    "asset_display_name",
    "machine_group",
    "criticality",
    "location",
    "status_category",     # Open / Closed / Review
    "request_state",
    "is_open",
    "ttr_hours",
    "maintenance_job_type",
    "job_trade",
    "priority",
    "service_level",
    "data_quality_flag",
    "start_time",
    "end_time",
    "mapped_stage",
)

# Fields explicitly considered sensitive (dropped even if added to a row later).
SENSITIVE_FIELDS = (
    "description", "translated_description", "description_original", "remarks",
    "started_by", "created_by", "technician", "assigned_technician", "staff",
    "vendor", "supplier", "contractor", "contractorOrPIC", "provider",
    "email", "phone", "cost", "price",
)

# Patterns that look like secrets / keys — redacted from any text we emit.
_SECRET_PATTERNS = [
    re.compile(r"(?i)(api[_-]?key|secret|token|password|bearer)\s*[:=]\s*\S+"),
    re.compile(r"sk-[A-Za-z0-9]{16,}"),
    re.compile(r"AKIA[0-9A-Z]{12,}"),
]


def redact_secrets(text):
    """Strip anything that looks like an API key / secret from a string."""
    if not isinstance(text, str):
        return text
    cleaned = text
    for pat in _SECRET_PATTERNS:
        cleaned = pat.sub("[REDACTED]", cleaned)
    return cleaned


def scrub_work_order_row(row: dict) -> dict:
    """Project one WO row onto the safe allowlist (default-deny)."""
    safe = {}
    for key in WORK_ORDER_ALLOWLIST:
        if key in row and row[key] not in (None, ""):
            value = row[key]
            safe[key] = redact_secrets(value) if isinstance(value, str) else value
    # Normalise the open/closed label without leaking lifecycle internals.
    if "status_category" not in safe:
        safe["status_category"] = "Open" if row.get("is_open") else "Closed"
    return safe


def limit_rows(rows, requested_limit=None):
    """Clamp a row list to the allowed window (never the full dataset)."""
    cap = config.ROW_CAP_DEFAULT
    if requested_limit:
        try:
            cap = max(1, min(int(requested_limit), config.ROW_CAP_MAX))
        except (TypeError, ValueError):
            cap = config.ROW_CAP_DEFAULT
    return list(rows)[:cap]


def guard_work_orders(query_result: dict, requested_limit=None) -> dict:
    """KPI Summary -> Limited Filtered Rows: scrub + cap a WO query result."""
    rows = query_result.get("rows", []) or []
    total_matched = query_result.get("total_matched", len(rows))
    scrubbed = [scrub_work_order_row(r) for r in rows]
    capped = limit_rows(scrubbed, requested_limit)
    return {
        "mode": "limited_filtered_rows",
        "window": query_result.get("window"),
        "stage": query_result.get("stage"),
        "total_matched": total_matched,
        "returned_rows": len(capped),
        "row_cap": config.ROW_CAP_MAX,
        "fields": list(WORK_ORDER_ALLOWLIST),
        "rows": capped,
        "truncated": total_matched > len(capped),
        "note": "Limited, field-reduced view. Full work-order records are never returned.",
        "draft_label": config.DRAFT_LABEL,
        "console_safe": True,
    }


def guard_summary(payload, *, mode="kpi_summary") -> dict:
    """Wrap a KPI summary/dict so it is safe to ship to the chatbot frontend."""
    safe_payload = _deep_redact(payload)
    return {
        "mode": mode,
        "data": safe_payload,
        "draft_label": config.DRAFT_LABEL,
        "console_safe": True,        # contains no raw row dumps
        "contains_raw_rows": False,
    }


def block_full_dataset(requested_rows) -> None:
    """Defensive guard: refuse anything that smells like a full-dataset dump."""
    try:
        n = len(requested_rows)
    except TypeError:
        return
    if n > config.ROW_CAP_MAX:
        raise PermissionError(
            f"MIRA privacy guard blocked a {n}-row transfer "
            f"(cap is {config.ROW_CAP_MAX}). Use KPI Summary Mode or narrow the filter."
        )


def mark_draft(text: str) -> str:
    """Stamp the standard review label onto a generated narrative."""
    body = redact_secrets(text or "").rstrip()
    return f"{body}\n\n— {config.DRAFT_LABEL}."


def _deep_redact(value):
    """Recursively drop sensitive keys and redact secret-looking strings."""
    if isinstance(value, dict):
        out = {}
        for k, v in value.items():
            if k in SENSITIVE_FIELDS:
                continue
            out[k] = _deep_redact(v)
        return out
    if isinstance(value, list):
        return [_deep_redact(v) for v in value]
    if isinstance(value, str):
        return redact_secrets(value)
    return value
